export default{
    name:"testimonials",
    title:"Testimonials",
    type:"document",
    fields:[
        {
            name:"name",
            title:"Name",
            type:"string"
        },
        {
            name:"company",
            title:"Company",
            type:"string"
        },
        {
            name:"imageurl",
            title:"ImgUrl",
            type:"image",
            options:{
                hotspot:true, //when user uploading the image, they can crop the image the way user want
            }
        },
        {
            name:"feedback",
            title:"Feedback",
            type:"string"
        },
    ]
}